name: release

on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: bash release.sh "${{ github.ref }}"

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Vincent Young
          author_email: missuo@pm.me
          message: "update version"

      - name: Push changes
        uses: EndBug/git-push@v2
        with:
          branch: main
          force: true # Optional, use it only if you need to force push
          github_token: ${{ secrets.GITHUB_TOKEN }}
